name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [^19] # Specify Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

 - name: Check if PR is mergeable
      run: |
        if [ "$(jq -r .pull_request.mergeable $GITHUB_EVENT_PATH)" != "true" ]; then
          echo "Pull request is not mergeable, please resolve conflicts."
          exit 1
        fi
